import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Pilota St André - comptes</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1>Aupa Txapeldun !</h1>
			</main>

			<footer className={styles.footer}>
				<p>Le pied !</p>
			</footer>
		</div>
	)
}
